### ISSUE TITLE
icon for CutableTextView

### ISSUE THREAD

**Issue by somratking420** [Devit951/CutableTextView#2]
Hi @Devit951 , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by PopPsyA** [comment]
Hi @somratking420 it's really nice suggestion :) If it's free , show me your logo.

**Comment by somratking420** [comment]
hi @Devit951 ,which logo do you like.
![text-01](https://user-images.githubusercontent.com/40878798/42724033-b731fd52-878c-11e8-8d32-75a7f3cf5e49.jpg)

**Comment by PopPsyA** [comment]
**d** looks like good

**Comment by somratking420** [comment]
hi @Devit951 , I've uploaded the logo to the drive, this is the link.https://drive.google.com/open?id=1e35jKDSV1yVBthOiZa9Ollh-Gza4GkXl

and also I have sent a pull request for you, check #3

**Comment by PopPsyA** [comment]
Can you make icon smaller and make pull request again?

**Comment by somratking420** [comment]
sir,it's best?

**Comment by PopPsyA** [comment]
@somratking420 Yes , but crop size of logo to 400x400

**Comment by somratking420** [comment]
sir, tell your icon size.?

**Comment by PopPsyA** [comment]
Sorry i don't need icon , only logo. Please update your logo to 400x400 in Readme.

**Comment by somratking420** [comment]
ok,sir
